{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Sagemaker setup of MNIST classifier"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Import SageMaker [Python SDK](https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html) into our project, and **Pytorch Estimator**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sagemaker\n",
    "from sagemaker.pytorch import PyTorch"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Create a session object, which initializes data related to execution role"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "sagemaker_session = sagemaker.Session()\n",
    "\n",
    "bucket = 's3://dataset.mnist'\n",
    "role = sagemaker.get_execution_role()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "estimator = PyTorch(entry_point='train.py',\n",
    "                    source_dir='../code',\n",
    "                    role=role,\n",
    "                    framework_version='1.4.0',\n",
    "                    train_instance_count=1,\n",
    "                    train_instance_type='ml.p2.xlarge',\n",
    "                    hyperparameters={\n",
    "                        'epochs': 6,\n",
    "                        'batch-size': 128,\n",
    "                    })\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "'create_image_uri' will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.\n",
      "'s3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.\n",
      "'s3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.\n",
      "'create_image_uri' will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2020-07-13 13:04:37 Starting - Starting the training job...\n",
      "2020-07-13 13:04:39 Starting - Launching requested ML instances......\n",
      "2020-07-13 13:05:46 Starting - Preparing the instances for training......\n",
      "2020-07-13 13:07:03 Downloading - Downloading input data....................................\n",
      "2020-07-13 13:13:11 Training - Training image download completed. Training in progress..\u001b[34mbash: cannot set terminal process group (-1): Inappropriate ioctl for device\u001b[0m\n",
      "\u001b[34mbash: no job control in this shell\u001b[0m\n",
      "\u001b[34m2020-07-13 13:13:13,037 sagemaker-containers INFO     Imported framework sagemaker_pytorch_container.training\u001b[0m\n",
      "\u001b[34m2020-07-13 13:13:13,061 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.\u001b[0m\n",
      "\u001b[34m2020-07-13 13:13:14,484 sagemaker_pytorch_container.training INFO     Invoking user training script.\u001b[0m\n",
      "\u001b[34m2020-07-13 13:13:14,838 sagemaker-containers INFO     Module default_user_module_name does not provide a setup.py. \u001b[0m\n",
      "\u001b[34mGenerating setup.py\u001b[0m\n",
      "\u001b[34m2020-07-13 13:13:14,839 sagemaker-containers INFO     Generating setup.cfg\u001b[0m\n",
      "\u001b[34m2020-07-13 13:13:14,839 sagemaker-containers INFO     Generating MANIFEST.in\u001b[0m\n",
      "\u001b[34m2020-07-13 13:13:14,839 sagemaker-containers INFO     Installing module with the following command:\u001b[0m\n",
      "\u001b[34m/opt/conda/bin/python -m pip install . -r requirements.txt\u001b[0m\n",
      "\u001b[34mProcessing /tmp/tmp7fk17u99/module_dir\u001b[0m\n",
      "\u001b[34mCollecting absl-py==0.9.0\n",
      "  Downloading absl-py-0.9.0.tar.gz (104 kB)\u001b[0m\n",
      "\u001b[34mCollecting boto3==1.14.20\n",
      "  Downloading boto3-1.14.20-py2.py3-none-any.whl (128 kB)\u001b[0m\n",
      "\u001b[34mCollecting botocore==1.17.20\n",
      "  Downloading botocore-1.17.20-py2.py3-none-any.whl (6.3 MB)\u001b[0m\n",
      "\u001b[34mCollecting cachetools==4.1.1\n",
      "  Downloading cachetools-4.1.1-py3-none-any.whl (10 kB)\u001b[0m\n",
      "\u001b[34mCollecting certifi==2020.6.20\n",
      "  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: chardet==3.0.4 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 7)) (3.0.4)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: docutils==0.15.2 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 8)) (0.15.2)\u001b[0m\n",
      "\u001b[34mCollecting future==0.18.2\n",
      "  Downloading future-0.18.2.tar.gz (829 kB)\u001b[0m\n",
      "\u001b[34mCollecting google-auth-oauthlib==0.4.1\n",
      "  Downloading google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)\u001b[0m\n",
      "\u001b[34mCollecting google-auth==1.18.0\n",
      "  Downloading google_auth-1.18.0-py2.py3-none-any.whl (90 kB)\u001b[0m\n",
      "\u001b[34mCollecting grpcio==1.30.0\n",
      "  Downloading grpcio-1.30.0-cp36-cp36m-manylinux2010_x86_64.whl (3.0 MB)\u001b[0m\n",
      "\u001b[34mCollecting idna==2.10\n",
      "  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)\u001b[0m\n",
      "\u001b[34mCollecting importlib-metadata==1.7.0\n",
      "  Downloading importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: jmespath==0.10.0 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 15)) (0.10.0)\u001b[0m\n",
      "\u001b[34mCollecting markdown==3.2.2\n",
      "  Downloading Markdown-3.2.2-py3-none-any.whl (88 kB)\u001b[0m\n",
      "\u001b[34mCollecting numpy==1.19.0\n",
      "  Downloading numpy-1.19.0-cp36-cp36m-manylinux2010_x86_64.whl (14.6 MB)\u001b[0m\n",
      "\u001b[34mCollecting oauthlib==3.1.0\n",
      "  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: packaging==20.4 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 19)) (20.4)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: protobuf3-to-dict==0.1.5 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 20)) (0.1.5)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: protobuf==3.12.2 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 21)) (3.12.2)\u001b[0m\n",
      "\u001b[34mCollecting pyasn1-modules==0.2.8\n",
      "  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyasn1==0.4.8 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 23)) (0.4.8)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyparsing==2.4.7 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 24)) (2.4.7)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: python-dateutil==2.8.1 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 25)) (2.8.1)\u001b[0m\n",
      "\u001b[34mCollecting pytorch-lightning==0.8.5\n",
      "  Downloading pytorch_lightning-0.8.5-py3-none-any.whl (313 kB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyyaml==5.3.1 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 27)) (5.3.1)\u001b[0m\n",
      "\u001b[34mCollecting requests-oauthlib==1.3.0\n",
      "  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)\u001b[0m\n",
      "\u001b[34mCollecting requests==2.24.0\n",
      "  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)\u001b[0m\n",
      "\u001b[34mCollecting rsa==4.6\n",
      "  Downloading rsa-4.6-py3-none-any.whl (47 kB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: s3transfer==0.3.3 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 31)) (0.3.3)\u001b[0m\n",
      "\u001b[34mCollecting sagemaker==1.69.0\n",
      "  Downloading sagemaker-1.69.0.tar.gz (296 kB)\u001b[0m\n",
      "\u001b[34mCollecting scipy==1.5.1\n",
      "  Downloading scipy-1.5.1-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)\u001b[0m\n",
      "\u001b[34mCollecting six==1.15.0\n",
      "  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)\u001b[0m\n",
      "\u001b[34mCollecting smdebug-rulesconfig==0.1.4\n",
      "  Downloading smdebug_rulesconfig-0.1.4-py2.py3-none-any.whl (10 kB)\u001b[0m\n",
      "\u001b[34mCollecting tensorboard-plugin-wit==1.7.0\n",
      "  Downloading tensorboard_plugin_wit-1.7.0-py3-none-any.whl (779 kB)\u001b[0m\n",
      "\u001b[34mCollecting tensorboard==2.2.2\n",
      "  Downloading tensorboard-2.2.2-py3-none-any.whl (3.0 MB)\u001b[0m\n",
      "\u001b[34mCollecting torch==1.5.1\n",
      "  Downloading torch-1.5.1-cp36-cp36m-manylinux1_x86_64.whl (753.2 MB)\u001b[0m\n",
      "\u001b[34mCollecting tqdm==4.47.0\n",
      "  Downloading tqdm-4.47.0-py2.py3-none-any.whl (66 kB)\u001b[0m\n",
      "\u001b[34mCollecting urllib3==1.25.9\n",
      "  Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: werkzeug==1.0.1 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 41)) (1.0.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: wheel==0.34.2 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 42)) (0.34.2)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: zipp==3.1.0 in /opt/conda/lib/python3.6/site-packages (from -r requirements.txt (line 43)) (3.1.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: setuptools>=40.3.0 in /opt/conda/lib/python3.6/site-packages (from google-auth==1.18.0->-r requirements.txt (line 11)) (46.4.0.post20200518)\u001b[0m\n",
      "\u001b[34mBuilding wheels for collected packages: absl-py, future, sagemaker, default-user-module-name\n",
      "  Building wheel for absl-py (setup.py): started\n",
      "  Building wheel for absl-py (setup.py): finished with status 'done'\n",
      "  Created wheel for absl-py: filename=absl_py-0.9.0-py3-none-any.whl size=121931 sha256=d36ea27ba24b2d652ab5e36074d533d28496efe18c0dba78e266b6776edc2149\n",
      "  Stored in directory: /root/.cache/pip/wheels/c3/af/84/3962a6af7b4ab336e951b7877dcfb758cf94548bb1771e0679\n",
      "  Building wheel for future (setup.py): started\u001b[0m\n",
      "\u001b[34m  Building wheel for future (setup.py): finished with status 'done'\n",
      "  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=bf241790f31df521b0568d9548e7d17ecee1c36e98cc662ebc2bb1ed0c712b0d\n",
      "  Stored in directory: /root/.cache/pip/wheels/6e/9c/ed/4499c9865ac1002697793e0ae05ba6be33553d098f3347fb94\n",
      "  Building wheel for sagemaker (setup.py): started\n",
      "  Building wheel for sagemaker (setup.py): finished with status 'done'\n",
      "  Created wheel for sagemaker: filename=sagemaker-1.69.0-py2.py3-none-any.whl size=384828 sha256=6932dd7ec9bf42671f101eebb8a13f776c90d690f211f4b44c532e9918feb08e\n",
      "  Stored in directory: /root/.cache/pip/wheels/43/11/be/445ade3de346b409945d1275aa2e46dd79fb6dcedff0417d1d\n",
      "  Building wheel for default-user-module-name (setup.py): started\u001b[0m\n",
      "\u001b[34m  Building wheel for default-user-module-name (setup.py): finished with status 'done'\n",
      "  Created wheel for default-user-module-name: filename=default_user_module_name-1.0.0-py2.py3-none-any.whl size=8193 sha256=fbd6f52066b476ceb4fe96dcc35abd4b0382592c00e33169301b54de51ce9fab\n",
      "  Stored in directory: /tmp/pip-ephem-wheel-cache-qdc6v6xn/wheels/8d/f2/d4/d9825ea9d81c8dd3b114e917ff0864d00eb14a9e06d85f95bc\u001b[0m\n",
      "\u001b[34mSuccessfully built absl-py future sagemaker default-user-module-name\u001b[0m\n",
      "\u001b[34mERROR: torchvision 0.5.0 has requirement torch==1.4.0, but you'll have torch 1.5.1 which is incompatible.\u001b[0m\n",
      "\u001b[34mERROR: awscli 1.18.73 has requirement botocore==1.16.23, but you'll have botocore 1.17.20 which is incompatible.\u001b[0m\n",
      "\u001b[34mERROR: awscli 1.18.73 has requirement rsa<=3.5.0,>=3.1.2, but you'll have rsa 4.6 which is incompatible.\u001b[0m\n",
      "\u001b[34mInstalling collected packages: six, absl-py, urllib3, botocore, boto3, cachetools, certifi, future, oauthlib, idna, requests, requests-oauthlib, rsa, pyasn1-modules, google-auth, google-auth-oauthlib, grpcio, importlib-metadata, markdown, numpy, tensorboard-plugin-wit, tensorboard, tqdm, torch, pytorch-lightning, scipy, smdebug-rulesconfig, sagemaker, default-user-module-name\n",
      "  Attempting uninstall: six\n",
      "    Found existing installation: six 1.14.0\n",
      "    Uninstalling six-1.14.0:\u001b[0m\n",
      "\u001b[34m      Successfully uninstalled six-1.14.0\n",
      "  Attempting uninstall: urllib3\n",
      "    Found existing installation: urllib3 1.25.8\n",
      "    Uninstalling urllib3-1.25.8:\n",
      "      Successfully uninstalled urllib3-1.25.8\n",
      "  Attempting uninstall: botocore\n",
      "    Found existing installation: botocore 1.16.23\n",
      "    Uninstalling botocore-1.16.23:\n",
      "      Successfully uninstalled botocore-1.16.23\u001b[0m\n",
      "\u001b[34m  Attempting uninstall: boto3\n",
      "    Found existing installation: boto3 1.13.23\n",
      "    Uninstalling boto3-1.13.23:\n",
      "      Successfully uninstalled boto3-1.13.23\n",
      "  Attempting uninstall: certifi\n",
      "    Found existing installation: certifi 2020.4.5.1\n",
      "    Uninstalling certifi-2020.4.5.1:\n",
      "      Successfully uninstalled certifi-2020.4.5.1\n",
      "  Attempting uninstall: future\n",
      "    Found existing installation: future 0.17.1\n",
      "    Uninstalling future-0.17.1:\n",
      "      Successfully uninstalled future-0.17.1\u001b[0m\n",
      "\u001b[34m  Attempting uninstall: idna\n",
      "    Found existing installation: idna 2.8\n",
      "    Uninstalling idna-2.8:\n",
      "      Successfully uninstalled idna-2.8\n",
      "  Attempting uninstall: requests\n",
      "    Found existing installation: requests 2.22.0\n",
      "    Uninstalling requests-2.22.0:\n",
      "      Successfully uninstalled requests-2.22.0\n",
      "  Attempting uninstall: rsa\n",
      "    Found existing installation: rsa 3.4.2\n",
      "    Uninstalling rsa-3.4.2:\n",
      "      Successfully uninstalled rsa-3.4.2\u001b[0m\n",
      "\u001b[34m  Attempting uninstall: importlib-metadata\n",
      "    Found existing installation: importlib-metadata 1.6.0\n",
      "    Uninstalling importlib-metadata-1.6.0:\n",
      "      Successfully uninstalled importlib-metadata-1.6.0\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 1.16.4\n",
      "    Uninstalling numpy-1.16.4:\n",
      "      Successfully uninstalled numpy-1.16.4\u001b[0m\n",
      "\u001b[34m  Attempting uninstall: tqdm\n",
      "    Found existing installation: tqdm 4.42.1\n",
      "    Uninstalling tqdm-4.42.1:\n",
      "      Successfully uninstalled tqdm-4.42.1\n",
      "  Attempting uninstall: torch\n",
      "    Found existing installation: torch 1.4.0\n",
      "    Uninstalling torch-1.4.0:\n",
      "      Successfully uninstalled torch-1.4.0\u001b[0m\n",
      "\u001b[34m  Attempting uninstall: scipy\n",
      "    Found existing installation: scipy 1.2.2\n",
      "    Uninstalling scipy-1.2.2:\n",
      "      Successfully uninstalled scipy-1.2.2\u001b[0m\n",
      "\u001b[34m  Attempting uninstall: smdebug-rulesconfig\n",
      "    Found existing installation: smdebug-rulesconfig 0.1.2\n",
      "    Uninstalling smdebug-rulesconfig-0.1.2:\n",
      "      Successfully uninstalled smdebug-rulesconfig-0.1.2\n",
      "  Attempting uninstall: sagemaker\n",
      "    Found existing installation: sagemaker 1.50.17\n",
      "    Uninstalling sagemaker-1.50.17:\n",
      "      Successfully uninstalled sagemaker-1.50.17\u001b[0m\n",
      "\u001b[34mSuccessfully installed absl-py-0.9.0 boto3-1.14.20 botocore-1.17.20 cachetools-4.1.1 certifi-2020.6.20 default-user-module-name-1.0.0 future-0.18.2 google-auth-1.18.0 google-auth-oauthlib-0.4.1 grpcio-1.30.0 idna-2.10 importlib-metadata-1.7.0 markdown-3.2.2 numpy-1.19.0 oauthlib-3.1.0 pyasn1-modules-0.2.8 pytorch-lightning-0.8.5 requests-2.24.0 requests-oauthlib-1.3.0 rsa-4.6 sagemaker-1.69.0 scipy-1.5.1 six-1.15.0 smdebug-rulesconfig-0.1.4 tensorboard-2.2.2 tensorboard-plugin-wit-1.7.0 torch-1.5.1 tqdm-4.47.0 urllib3-1.25.9\u001b[0m\n",
      "\u001b[34m2020-07-13 13:14:48,434 sagemaker-containers INFO     Invoking user script\n",
      "\u001b[0m\n",
      "\u001b[34mTraining Env:\n",
      "\u001b[0m\n",
      "\u001b[34m{\n",
      "    \"additional_framework_parameters\": {},\n",
      "    \"channel_input_dirs\": {\n",
      "        \"test\": \"/opt/ml/input/data/test\",\n",
      "        \"train\": \"/opt/ml/input/data/train\"\n",
      "    },\n",
      "    \"current_host\": \"algo-1\",\n",
      "    \"framework_module\": \"sagemaker_pytorch_container.training:main\",\n",
      "    \"hosts\": [\n",
      "        \"algo-1\"\n",
      "    ],\n",
      "    \"hyperparameters\": {\n",
      "        \"batch-size\": 128,\n",
      "        \"epochs\": 6\n",
      "    },\n",
      "    \"input_config_dir\": \"/opt/ml/input/config\",\n",
      "    \"input_data_config\": {\n",
      "        \"test\": {\n",
      "            \"TrainingInputMode\": \"File\",\n",
      "            \"S3DistributionType\": \"FullyReplicated\",\n",
      "            \"RecordWrapperType\": \"None\"\n",
      "        },\n",
      "        \"train\": {\n",
      "            \"TrainingInputMode\": \"File\",\n",
      "            \"S3DistributionType\": \"FullyReplicated\",\n",
      "            \"RecordWrapperType\": \"None\"\n",
      "        }\n",
      "    },\n",
      "    \"input_dir\": \"/opt/ml/input\",\n",
      "    \"is_master\": true,\n",
      "    \"job_name\": \"pytorch-training-2020-07-13-13-04-36-994\",\n",
      "    \"log_level\": 20,\n",
      "    \"master_hostname\": \"algo-1\",\n",
      "    \"model_dir\": \"/opt/ml/model\",\n",
      "    \"module_dir\": \"s3://sagemaker-eu-west-1-682411330166/pytorch-training-2020-07-13-13-04-36-994/source/sourcedir.tar.gz\",\n",
      "    \"module_name\": \"train\",\n",
      "    \"network_interface_name\": \"eth0\",\n",
      "    \"num_cpus\": 4,\n",
      "    \"num_gpus\": 1,\n",
      "    \"output_data_dir\": \"/opt/ml/output/data\",\n",
      "    \"output_dir\": \"/opt/ml/output\",\n",
      "    \"output_intermediate_dir\": \"/opt/ml/output/intermediate\",\n",
      "    \"resource_config\": {\n",
      "        \"current_host\": \"algo-1\",\n",
      "        \"hosts\": [\n",
      "            \"algo-1\"\n",
      "        ],\n",
      "        \"network_interface_name\": \"eth0\"\n",
      "    },\n",
      "    \"user_entry_point\": \"train.py\"\u001b[0m\n",
      "\u001b[34m}\n",
      "\u001b[0m\n",
      "\u001b[34mEnvironment variables:\n",
      "\u001b[0m\n",
      "\u001b[34mSM_HOSTS=[\"algo-1\"]\u001b[0m\n",
      "\u001b[34mSM_NETWORK_INTERFACE_NAME=eth0\u001b[0m\n",
      "\u001b[34mSM_HPS={\"batch-size\":128,\"epochs\":6}\u001b[0m\n",
      "\u001b[34mSM_USER_ENTRY_POINT=train.py\u001b[0m\n",
      "\u001b[34mSM_FRAMEWORK_PARAMS={}\u001b[0m\n",
      "\u001b[34mSM_RESOURCE_CONFIG={\"current_host\":\"algo-1\",\"hosts\":[\"algo-1\"],\"network_interface_name\":\"eth0\"}\u001b[0m\n",
      "\u001b[34mSM_INPUT_DATA_CONFIG={\"test\":{\"RecordWrapperType\":\"None\",\"S3DistributionType\":\"FullyReplicated\",\"TrainingInputMode\":\"File\"},\"train\":{\"RecordWrapperType\":\"None\",\"S3DistributionType\":\"FullyReplicated\",\"TrainingInputMode\":\"File\"}}\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_DATA_DIR=/opt/ml/output/data\u001b[0m\n",
      "\u001b[34mSM_CHANNELS=[\"test\",\"train\"]\u001b[0m\n",
      "\u001b[34mSM_CURRENT_HOST=algo-1\u001b[0m\n",
      "\u001b[34mSM_MODULE_NAME=train\u001b[0m\n",
      "\u001b[34mSM_LOG_LEVEL=20\u001b[0m\n",
      "\u001b[34mSM_FRAMEWORK_MODULE=sagemaker_pytorch_container.training:main\u001b[0m\n",
      "\u001b[34mSM_INPUT_DIR=/opt/ml/input\u001b[0m\n",
      "\u001b[34mSM_INPUT_CONFIG_DIR=/opt/ml/input/config\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_DIR=/opt/ml/output\u001b[0m\n",
      "\u001b[34mSM_NUM_CPUS=4\u001b[0m\n",
      "\u001b[34mSM_NUM_GPUS=1\u001b[0m\n",
      "\u001b[34mSM_MODEL_DIR=/opt/ml/model\u001b[0m\n",
      "\u001b[34mSM_MODULE_DIR=s3://sagemaker-eu-west-1-682411330166/pytorch-training-2020-07-13-13-04-36-994/source/sourcedir.tar.gz\u001b[0m\n",
      "\u001b[34mSM_TRAINING_ENV={\"additional_framework_parameters\":{},\"channel_input_dirs\":{\"test\":\"/opt/ml/input/data/test\",\"train\":\"/opt/ml/input/data/train\"},\"current_host\":\"algo-1\",\"framework_module\":\"sagemaker_pytorch_container.training:main\",\"hosts\":[\"algo-1\"],\"hyperparameters\":{\"batch-size\":128,\"epochs\":6},\"input_config_dir\":\"/opt/ml/input/config\",\"input_data_config\":{\"test\":{\"RecordWrapperType\":\"None\",\"S3DistributionType\":\"FullyReplicated\",\"TrainingInputMode\":\"File\"},\"train\":{\"RecordWrapperType\":\"None\",\"S3DistributionType\":\"FullyReplicated\",\"TrainingInputMode\":\"File\"}},\"input_dir\":\"/opt/ml/input\",\"is_master\":true,\"job_name\":\"pytorch-training-2020-07-13-13-04-36-994\",\"log_level\":20,\"master_hostname\":\"algo-1\",\"model_dir\":\"/opt/ml/model\",\"module_dir\":\"s3://sagemaker-eu-west-1-682411330166/pytorch-training-2020-07-13-13-04-36-994/source/sourcedir.tar.gz\",\"module_name\":\"train\",\"network_interface_name\":\"eth0\",\"num_cpus\":4,\"num_gpus\":1,\"output_data_dir\":\"/opt/ml/output/data\",\"output_dir\":\"/opt/ml/output\",\"output_intermediate_dir\":\"/opt/ml/output/intermediate\",\"resource_config\":{\"current_host\":\"algo-1\",\"hosts\":[\"algo-1\"],\"network_interface_name\":\"eth0\"},\"user_entry_point\":\"train.py\"}\u001b[0m\n",
      "\u001b[34mSM_USER_ARGS=[\"--batch-size\",\"128\",\"--epochs\",\"6\"]\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate\u001b[0m\n",
      "\u001b[34mSM_CHANNEL_TEST=/opt/ml/input/data/test\u001b[0m\n",
      "\u001b[34mSM_CHANNEL_TRAIN=/opt/ml/input/data/train\u001b[0m\n",
      "\u001b[34mSM_HP_BATCH-SIZE=128\u001b[0m\n",
      "\u001b[34mSM_HP_EPOCHS=6\u001b[0m\n",
      "\u001b[34mPYTHONPATH=/opt/ml/code:/opt/conda/bin:/opt/conda/lib/python36.zip:/opt/conda/lib/python3.6:/opt/conda/lib/python3.6/lib-dynload:/opt/conda/lib/python3.6/site-packages\n",
      "\u001b[0m\n",
      "\u001b[34mInvoking script with the following command:\n",
      "\u001b[0m\n",
      "\u001b[34m/opt/conda/bin/python train.py --batch-size 128 --epochs 6\n",
      "\n",
      "\u001b[0m\n",
      "\n",
      "2020-07-13 13:15:10 Uploading - Uploading generated training model\n",
      "2020-07-13 13:15:10 Failed - Training job failed\n",
      "\u001b[34mNamespace(batch_size=128, epochs=6, gpus=1, model_dir=None, output_data_dir=None, test=None, train=None)\u001b[0m\n",
      "\u001b[34m2020-07-13 13:14:59,636 sagemaker-containers ERROR    ExecuteUserScriptError:\u001b[0m\n",
      "\u001b[34mCommand \"/opt/conda/bin/python train.py --batch-size 128 --epochs 6\"\u001b[0m\n",
      "\u001b[34mGPU available: True, used: True\u001b[0m\n",
      "\u001b[34mTPU available: False, using: 0 TPU cores\u001b[0m\n",
      "\u001b[34mCUDA_VISIBLE_DEVICES: [0]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"train.py\", line 36, in <module>\n",
      "    mnistTrainer.fit(model)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py\", line 944, in fit\n",
      "    model.prepare_data()\n",
      "  File \"/opt/ml/code/MNISTClassifier.py\", line 64, in prepare_data\n",
      "    self.train_loader, self.val_loader, self.test_loader  = self.load_split_train_test()\n",
      "  File \"/opt/ml/code/MNISTClassifier.py\", line 43, in load_split_train_test\n",
      "    train_data = datasets.ImageFolder(self.train_data_dir, transform=train_transforms)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/torchvision/datasets/folder.py\", line 209, in __init__\n",
      "    is_valid_file=is_valid_file)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/torchvision/datasets/folder.py\", line 94, in __init__\n",
      "    samples = make_dataset(self.root, class_to_idx, extensions, is_valid_file)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/torchvision/datasets/folder.py\", line 37, in make_dataset\n",
      "    dir = os.path.expanduser(dir)\n",
      "  File \"/opt/conda/lib/python3.6/posixpath.py\", line 235, in expanduser\n",
      "    path = os.fspath(path)\u001b[0m\n",
      "\u001b[34mTypeError: expected str, bytes or os.PathLike object, not NoneType\u001b[0m\n"
     ]
    },
    {
     "ename": "UnexpectedStatusException",
     "evalue": "Error for Training job pytorch-training-2020-07-13-13-04-36-994: Failed. Reason: AlgorithmError: ExecuteUserScriptError:\nCommand \"/opt/conda/bin/python train.py --batch-size 128 --epochs 6\"\nGPU available: True, used: True\nTPU available: False, using: 0 TPU cores\nCUDA_VISIBLE_DEVICES: [0]\nTraceback (most recent call last):\n  File \"train.py\", line 36, in <module>\n    mnistTrainer.fit(model)\n  File \"/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py\", line 944, in fit\n    model.prepare_data()\n  File \"/opt/ml/code/MNISTClassifier.py\", line 64, in prepare_data\n    self.train_loader, self.val_loader, self.test_loader  = self.load_split_train_test()\n  File \"/opt/ml/code/MNISTClassifier.py\", line 43, in load_split_train_test\n    train_data = datasets.ImageFolder(self.train_data_dir, transform=train_transforms)\n  File \"/opt/conda/lib/python3.6/site-packages/torchvision/datasets/folder.py\", line 209, in __init__\n    is_valid_file=is_valid_file)\n  File \"/opt/conda/lib/python3.6/site-packages/torchvision/datasets/folder.py\", line 94, in __init__\n    samples = make_dataset(sel",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-12-0af45cd7f27d>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m estimator.fit({\n\u001b[1;32m      2\u001b[0m     \u001b[0;34m'train'\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mbucket\u001b[0m\u001b[0;34m+\u001b[0m\u001b[0;34m'/training'\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m     \u001b[0;34m'test'\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mbucket\u001b[0m\u001b[0;34m+\u001b[0m\u001b[0;34m'/testing'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m })\n",
      "\u001b[0;32m~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, inputs, wait, logs, job_name, experiment_config)\u001b[0m\n\u001b[1;32m    495\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjobs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_training_job\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    496\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 497\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_training_job\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    498\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    499\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_compilation_job_name\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, logs)\u001b[0m\n\u001b[1;32m   1112\u001b[0m         \u001b[0;31m# If logs are requested, call logs_for_jobs.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1113\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlogs\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0;34m\"None\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1114\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlogs_for_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlog_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1115\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1116\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait_for_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36mlogs_for_job\u001b[0;34m(self, job_name, wait, poll, log_type)\u001b[0m\n\u001b[1;32m   3068\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3069\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3070\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_check_job_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdescription\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"TrainingJobStatus\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3071\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mdot\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3072\u001b[0m                 \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36m_check_job_status\u001b[0;34m(self, job, desc, status_key_name)\u001b[0m\n\u001b[1;32m   2662\u001b[0m                 ),\n\u001b[1;32m   2663\u001b[0m                 \u001b[0mallowed_statuses\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"Completed\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"Stopped\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2664\u001b[0;31m                 \u001b[0mactual_status\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mstatus\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2665\u001b[0m             )\n\u001b[1;32m   2666\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m: Error for Training job pytorch-training-2020-07-13-13-04-36-994: Failed. Reason: AlgorithmError: ExecuteUserScriptError:\nCommand \"/opt/conda/bin/python train.py --batch-size 128 --epochs 6\"\nGPU available: True, used: True\nTPU available: False, using: 0 TPU cores\nCUDA_VISIBLE_DEVICES: [0]\nTraceback (most recent call last):\n  File \"train.py\", line 36, in <module>\n    mnistTrainer.fit(model)\n  File \"/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py\", line 944, in fit\n    model.prepare_data()\n  File \"/opt/ml/code/MNISTClassifier.py\", line 64, in prepare_data\n    self.train_loader, self.val_loader, self.test_loader  = self.load_split_train_test()\n  File \"/opt/ml/code/MNISTClassifier.py\", line 43, in load_split_train_test\n    train_data = datasets.ImageFolder(self.train_data_dir, transform=train_transforms)\n  File \"/opt/conda/lib/python3.6/site-packages/torchvision/datasets/folder.py\", line 209, in __init__\n    is_valid_file=is_valid_file)\n  File \"/opt/conda/lib/python3.6/site-packages/torchvision/datasets/folder.py\", line 94, in __init__\n    samples = make_dataset(sel"
     ]
    }
   ],
   "source": [
    "estimator.fit({\n",
    "    'train': bucket+'/training',\n",
    "    'test': bucket+'/testing'\n",
    "})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "conda_pytorch_p36",
   "language": "python",
   "name": "conda_pytorch_p36"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
